include(CMakeParseArguments)
include(CMakePushCheckState)
include(CheckCSourceCompiles)
include(CheckCXXSourceCompiles)
include(CheckSourceCompiles)

macro(_gpu_suite_prepare_probe prefix)
  cmake_push_check_state(RESET)
  set(CMAKE_REQUIRED_QUIET TRUE)
  set(CMAKE_REQUIRED_INCLUDES "${${prefix}_INCLUDES}")
  set(CMAKE_REQUIRED_LIBRARIES "${${prefix}_LIBRARIES}")
  set(CMAKE_REQUIRED_DEFINITIONS "${${prefix}_DEFINITIONS}")
  set(CMAKE_REQUIRED_LINK_OPTIONS "${${prefix}_LINK_OPTIONS}")
  if(${prefix}_COMPILE_OPTIONS)
    list(JOIN ${prefix}_COMPILE_OPTIONS " " _required_flags)
    set(CMAKE_REQUIRED_FLAGS "${_required_flags}")
  endif()
endmacro()

function(gpu_suite_check_c_link result)
  cmake_parse_arguments(PARSE_ARGV 1 PROBE "" "SOURCE"
    "INCLUDES;LIBRARIES;DEFINITIONS;COMPILE_OPTIONS;LINK_OPTIONS")
  if(NOT DEFINED PROBE_SOURCE)
    message(FATAL_ERROR "gpu_suite_check_c_link requires SOURCE")
  endif()
  _gpu_suite_prepare_probe(PROBE)
  unset(${result} CACHE)
  unset(${result})
  check_c_source_compiles("${PROBE_SOURCE}" ${result})
  set(${result} "${${result}}" PARENT_SCOPE)
  cmake_pop_check_state()
endfunction()

function(gpu_suite_check_cuda_link result)
  if(NOT CMAKE_CUDA_COMPILER_LOADED)
    set(${result} FALSE PARENT_SCOPE)
    return()
  endif()
  cmake_parse_arguments(PARSE_ARGV 1 PROBE "" "SOURCE"
    "INCLUDES;LIBRARIES;DEFINITIONS;COMPILE_OPTIONS;LINK_OPTIONS")
  if(NOT DEFINED PROBE_SOURCE)
    message(FATAL_ERROR "gpu_suite_check_cuda_link requires SOURCE")
  endif()
  _gpu_suite_prepare_probe(PROBE)
  unset(${result} CACHE)
  unset(${result})
  check_source_compiles(CUDA "${PROBE_SOURCE}" ${result})
  set(${result} "${${result}}" PARENT_SCOPE)
  cmake_pop_check_state()
endfunction()

function(gpu_suite_check_cxx_link result)
  cmake_parse_arguments(PARSE_ARGV 1 PROBE "" "SOURCE"
    "INCLUDES;LIBRARIES;DEFINITIONS;COMPILE_OPTIONS;LINK_OPTIONS")
  if(NOT DEFINED PROBE_SOURCE)
    message(FATAL_ERROR "gpu_suite_check_cxx_link requires SOURCE")
  endif()
  if("OpenACC::OpenACC_CXX" IN_LIST PROBE_LIBRARIES)
    list(APPEND PROBE_COMPILE_OPTIONS ${GPU_SUITE_OPENACC_COMPILE_OPTIONS})
    list(APPEND PROBE_LINK_OPTIONS ${GPU_SUITE_OPENACC_LINK_OPTIONS})
  endif()
  _gpu_suite_prepare_probe(PROBE)
  unset(${result} CACHE)
  unset(${result})
  check_cxx_source_compiles("${PROBE_SOURCE}" ${result})
  set(${result} "${${result}}" PARENT_SCOPE)
  cmake_pop_check_state()
endfunction()
