include(CheckLanguage)

macro(gpu_suite_enable_fortran)
  # CMake's NVHPC Release default contains -fast. Do not adopt that implicit
  # numerical profile for the new language, or change any C/C++ flags.
  set(CMAKE_Fortran_FLAGS_RELEASE "-O3" CACHE STRING "Fortran Release flags")
  set(CMAKE_Fortran_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "Fortran RelWithDebInfo flags")
  set(CMAKE_Fortran_FLAGS_MINSIZEREL "-O2" CACHE STRING "Fortran MinSizeRel flags")
  check_language(Fortran)
  if(NOT CMAKE_Fortran_COMPILER)
    message(FATAL_ERROR "Fortran was requested but no Fortran compiler is available")
  endif()
  enable_language(Fortran)
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
  set(_all_fortran_flags "${CMAKE_Fortran_FLAGS} ${CMAKE_Fortran_FLAGS_RELEASE} ${CMAKE_Fortran_FLAGS_RELWITHDEBINFO} ${CMAKE_Fortran_FLAGS_MINSIZEREL} ${CMAKE_Fortran_FLAGS_DEBUG}")
  if(_all_fortran_flags MATCHES "(^| )(-fast|-Ofast|-ffast-math|-fassociative-math|-ffinite-math-only|-Mflushz|-Mdaz|-Knoieee|-Mconcur|-stdpar|-acc|-mp|-gpu=|-fopenmp|-ftree-parallelize-loops|-floop-parallelize-all|-i8|-r8|-fdefault-integer-8|-fdefault-real-8)( |$|=|[^ ]+)")
    message(FATAL_ERROR "Unapproved numerical/parallel/offload option in Fortran flags: ${_all_fortran_flags}")
  endif()
  if(GPU_SUITE_BUILD_CPU AND (NOT GPU_SUITE_CPU_BLAS_BACKEND STREQUAL "ONEMKL" OR
     NOT GPU_SUITE_CPU_LAPACK_BACKEND STREQUAL "ONEMKL" OR
     NOT GPU_SUITE_CPU_SPARSE_BACKEND STREQUAL "ONEMKL" OR
     NOT GPU_SUITE_CPU_THRUST_BACKEND STREQUAL "STL"))
    message(FATAL_ERROR "Fortran CPU supports FFTW/oneMKL and intrinsic RNG/sum only; C/C++ alternative backend options do not select Fortran providers")
  endif()
  # The small C/C++ serialization bridge also performs finite-value checks.
  # Reject unsafe flags in this profile without modifying the C/C++ profile.
  foreach(_language C CXX)
    set(_bridge_flags "${CMAKE_${_language}_FLAGS} ${CMAKE_${_language}_FLAGS_RELEASE} ${CMAKE_${_language}_FLAGS_RELWITHDEBINFO} ${CMAKE_${_language}_FLAGS_MINSIZEREL} ${CMAKE_${_language}_FLAGS_DEBUG}")
    if(_bridge_flags MATCHES "(^| )(-fast|-Ofast|-ffast-math|-fassociative-math|-ffinite-math-only|-Mflushz|-Mdaz|-Knoieee)( |$)")
      message(FATAL_ERROR "Unsafe ${_language} flags in Fortran support: ${_bridge_flags}; explicitly select ordinary -O3/-O2 flags")
    endif()
  endforeach()
  if(CMAKE_Fortran_COMPILER_ID STREQUAL "NVHPC")
    set(GPU_SUITE_FORTRAN_SAFE_OPTIONS -Kieee -Mnoflushz -Mnodaz)
  elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
    set(GPU_SUITE_FORTRAN_SAFE_OPTIONS -fno-fast-math -ffp-contract=off)
  else()
    message(FATAL_ERROR "Fortran flags are validated for GNU and NVHPC only")
  endif()
  set(GPU_SUITE_FORTRAN_GPU_OPTIONS "")
  if(GPU_SUITE_BUILD_CUDA OR GPU_SUITE_BUILD_OPENACC)
    set(GPU_SUITE_CUDA_DISABLE_REASON "CUDA Fortran requires NVHPC and an external CUDA Toolkit/target")
    set(GPU_SUITE_OPENACC_DISABLE_REASON "OpenACC Fortran requires NVHPC and an external CUDA Toolkit/target")
    if(CMAKE_Fortran_COMPILER_ID STREQUAL "NVHPC")
      find_package(CUDAToolkit QUIET)
      if(CUDAToolkit_FOUND AND GPU_SUITE_NVHPC_GPU_TARGET MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$")
        _gpu_suite_resolve_cuda_toolkit_root(GPU_SUITE_CUDA_TOOLKIT_ROOT)
        if(NOT DEFINED ENV{NVHPC_CUDA_HOME} OR "$ENV{NVHPC_CUDA_HOME}" STREQUAL "")
          message(FATAL_ERROR "CUDA Fortran requires explicit NVHPC_CUDA_HOME")
        endif()
        file(REAL_PATH "$ENV{NVHPC_CUDA_HOME}" _fortran_cuda_home)
        if(NOT _fortran_cuda_home STREQUAL GPU_SUITE_CUDA_TOOLKIT_ROOT)
          message(FATAL_ERROR "Fortran CUDAToolkit root differs from NVHPC_CUDA_HOME")
        endif()
        set(GPU_SUITE_FORTRAN_GPU_OPTIONS -cuda "-gpu=${GPU_SUITE_NVHPC_GPU_TARGET},mem:separate")
        if(GPU_SUITE_BUILD_CUDA)
          set(GPU_SUITE_CUDA_TARGETS_ENABLED ON)
          set(GPU_SUITE_CUDA_DISABLE_REASON "")
        endif()
        if(GPU_SUITE_BUILD_OPENACC)
          set(GPU_SUITE_OPENACC_TARGETS_ENABLED ON)
          set(GPU_SUITE_OPENACC_DISABLE_REASON "")
        endif()
        # NVCC is needed only for the shared Thrust C++ object.
        if(DEFINED CMAKE_CUDA_ARCHITECTURES AND NOT CMAKE_CUDA_ARCHITECTURES STREQUAL "")
          check_language(CUDA)
          if(CMAKE_CUDA_COMPILER)
            enable_language(CUDA)
            set(GPU_SUITE_CUDA_LANGUAGE_ENABLED ON)
            set(_cuda_flags "${CMAKE_CUDA_FLAGS} ${CMAKE_CUDA_FLAGS_RELEASE} ${CMAKE_CUDA_FLAGS_RELWITHDEBINFO} ${CMAKE_CUDA_FLAGS_MINSIZEREL} ${CMAKE_CUDA_FLAGS_DEBUG}")
            if(_cuda_flags MATCHES "(^| )(--?use_fast_math|--?ftz=true|--?prec-div=false|--?prec-sqrt=false)( |$)")
              message(FATAL_ERROR "Unapproved CUDA numerical option in Fortran Thrust wrapper: ${_cuda_flags}")
            endif()
          endif()
        endif()
      endif()
    endif()
  endif()
endmacro()

function(gpu_suite_generate_fortran_metadata)
  string(TOUPPER "${CMAKE_BUILD_TYPE}" _config)
  set(_flags "${CMAKE_Fortran_FLAGS} ${CMAKE_Fortran_FLAGS_${_config}}")
  string(REPLACE ";" " " _flags "${_flags}")
  string(STRIP "${_flags}" _flags)
  _gpu_suite_escape_c_string("${CMAKE_Fortran_COMPILER_ID}" _compiler_c)
  _gpu_suite_escape_c_string("${CMAKE_Fortran_COMPILER_VERSION}" _version_c)
  _gpu_suite_escape_c_string("${_flags}" _flags_c)
  file(WRITE "${GPU_SUITE_GENERATED_INCLUDE_DIR}/gpu_suite/fortran_metadata.h"
    "#define GPU_SUITE_FORTRAN_COMPILER \"${_compiler_c}\"\n#define GPU_SUITE_FORTRAN_COMPILER_VERSION \"${_version_c}\"\n#define GPU_SUITE_FORTRAN_FLAGS \"${_flags_c}\"\n")
  foreach(_pair compiler version flags)
    if(_pair STREQUAL "compiler")
      set(_value "${CMAKE_Fortran_COMPILER_ID}")
    elseif(_pair STREQUAL "version")
      set(_value "${CMAKE_Fortran_COMPILER_VERSION}")
    else()
      set(_value "${_flags}")
    endif()
    _gpu_suite_escape_json_string("${_value}" _${_pair}_json)
  endforeach()
  _gpu_suite_escape_json_string("${GPU_SUITE_FORTRAN_GPU_OPTIONS}" _gpu_json)
  _gpu_suite_escape_json_string("${GPU_SUITE_FORTRAN_SAFE_OPTIONS}" _numerical_json)
  set(_acc_json "")
  if(GPU_SUITE_OPENACC_TARGETS_ENABLED)
    set(_acc_json "-acc=gpu")
  endif()
  file(READ "${GPU_SUITE_BUILD_METADATA_FILE}" _metadata)
  set(_fortran_json "\"fortran\":{\"compiler\":\"${_compiler_json}\",\"compiler_version\":\"${_version_json}\",\"cuda_target_options\":\"${_gpu_json}\",\"global_configure_flags\":\"${_flags_json}\",\"numerical_target_options\":\"${_numerical_json}\",\"openacc_target_option\":\"${_acc_json}\"},")
  string(REPLACE "\"git_commit\":" "${_fortran_json}\"git_commit\":" _metadata "${_metadata}")
  file(WRITE "${GPU_SUITE_BUILD_METADATA_FILE}" "${_metadata}")
  # The common metadata header must identify the final (Fortran-extended) file.
  file(SHA256 "${GPU_SUITE_BUILD_METADATA_FILE}" _digest)
  file(READ "${GPU_SUITE_GENERATED_INCLUDE_DIR}/gpu_suite/build_metadata.h" _header)
  string(REPLACE "${GPU_SUITE_BUILD_METADATA_SHA256}" "${_digest}" _header "${_header}")
  file(WRITE "${GPU_SUITE_GENERATED_INCLUDE_DIR}/gpu_suite/build_metadata.h" "${_header}")
  set(GPU_SUITE_BUILD_METADATA_SHA256 "${_digest}" CACHE INTERNAL "Build metadata hash" FORCE)
endfunction()

function(gpu_suite_fortran_probe output)
  cmake_parse_arguments(P "" "" "SOURCES;LIBRARIES;OPTIONS;INCLUDES" ${ARGN})
  set(_options ${GPU_SUITE_FORTRAN_SAFE_OPTIONS} ${P_OPTIONS})
  foreach(_include IN LISTS P_INCLUDES)
    list(APPEND _options "-I${_include}")
  endforeach()
  try_compile(_works "${CMAKE_BINARY_DIR}/fortran-probes/${output}"
    SOURCES ${P_SOURCES}
    COMPILE_DEFINITIONS ${_options}
    LINK_LIBRARIES ${P_LIBRARIES}
    LINK_OPTIONS ${GPU_SUITE_FORTRAN_SAFE_OPTIONS} ${P_OPTIONS}
    OUTPUT_VARIABLE _log)
  file(WRITE "${CMAKE_BINARY_DIR}/fortran-probes/${output}.log" "${_log}")
  set(${output} "${_works}" PARENT_SCOPE)
endfunction()
