function(gpu_suite_record_status label enabled reason)
  if(enabled)
    set(_state "ENABLED")
  else()
    set(_state "DISABLED")
  endif()
  set_property(GLOBAL APPEND PROPERTY GPU_SUITE_STATUS_LINES
               "${label}|${_state}|${reason}")
endfunction()

function(gpu_suite_print_status)
  get_property(_lines GLOBAL PROPERTY GPU_SUITE_STATUS_LINES)
  message(STATUS "")
  message(STATUS "GPU Library Suite configure summary")
  message(STATUS "-----------------------------------")
  foreach(_line IN LISTS _lines)
    string(REPLACE "|" ";" _parts "${_line}")
    list(GET _parts 0 _label)
    list(GET _parts 1 _state)
    list(GET _parts 2 _reason)
    if("${_reason}" STREQUAL "")
      message(STATUS "${_label}: ${_state}")
    else()
      message(STATUS "${_label}: ${_state} (${_reason})")
    endif()
  endforeach()
  message(STATUS "")
endfunction()
